export const eventItems = [
  {
    img: "./images/ClassReunion.jpg",
    alt: "Class-Reunion",
    date: "07",
    month: "feb",
    title: "Class Reunion",
    clockIcon: "far fa-clock",
    time: "11:00 am - 04:00 pm",
    place: "MGS Auditorium Hall",
    mapIcon: "fas fa-map-marker-alt",
  },
  {
    img: "./images/sports.jpg",
    alt: "Sports-Day",
    date: "15",
    month: "Jun",
    title: "Sports Day",
    clockIcon: "far fa-clock",
    time: "09:00 am - 03:00 pm",
    place: "MGS Sports Ground",
    mapIcon: "fas fa-map-marker-alt",
  },
  {
    img: "./images/annual.jpg",
    alt: "Annual-Function",
    date: "22",
    month: "Dec",
    title: "Annual Function 2021",
    clockIcon: "far fa-clock",
    time: "11:00 am - 04:00 pm",
    place: "MGS Auditorium Hall",
    mapIcon: "fas fa-map-marker-alt",
  },
];
